### ISSUE TITLE
Intermittent test failures with python3

### ISSUE THREAD

**Issue by luigino** [zopefoundation/ZODB#165]
As per subject, I'm experiencing test failures related to the 'storage namespace.
Could this be a race condition?

(see attachment)
[ZODB_py3_test.txt](https://github.com/zopefoundation/ZODB/files/1130350/ZODB_py3_test.txt)

**Comment by tseaver** [comment]
Thank you for the report!  AFAICT, this isn't a "namespace package" problem:  the doctests in `storages.rst` define a global variable named `storage` (created by calling `ZODB.config.storageFromString` with the value `base.fs`.  The initial assignment of that variable fails, which leads to the rest of the failures.

How are you invoking the tests?

**Comment by luigino** [comment]
Full disclosure, I'm packaging ZODB for openSUSE and running the build on OBS under kvm.
I've also noticed this problem with other zope packages (like zdaemon) but initially ascribed it to clashes between VM timing and hardcoded timeouts. Increasing them didn't help though.
I could not reproduce this locally.

Python2 tests are run immediately before and never fail, see log snippet:
```
+ /usr/bin/python3 setup.py test
running test
running egg_info
writing requirements to src/ZODB.egg-info/requires.txt
writing top-level names to src/ZODB.egg-info/top_level.txt
writing dependency_links to src/ZODB.egg-info/dependency_links.txt
writing entry points to src/ZODB.egg-info/entry_points.txt
writing src/ZODB.egg-info/PKG-INFO
reading manifest file 'src/ZODB.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'buildout.cfg'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
writing manifest file 'src/ZODB.egg-info/SOURCES.txt'
running build_ext
```

**Comment by jamadden** [comment]
The error:
```
     File "/home/abuild/rpmbuild/BUILD/ZODB-5.2.4/src/ZODB/FileStorage/FileStorage.py", line 1619, in read_index
        raise FileStorageFormatError(name)
    ZODB.FileStorage.FileStorage.FileStorageFormatError: base.fs
```

comes from [this Python code](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/FileStorage/FileStorage.py#L1619):
```python
read = file.read
...

if read(4) != packed_version:
   raise FileStorageFormatError(name)
```

So we know the file exists and can be read, but that it has the wrong contents.

`packed_version` is imported from `ZODB._compat.FILESTORAGE_MAGIC` and it has a different value depending on whether the code is [running on Python 2](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/_compat.py#L38)(`b"FS21"`) or [Python 3](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/_compat.py#L73)(`b"FS30"`).

So that suggests that the file was written with Python 2 and is now trying to be read with Python 3. Are you perhaps running these tests under both Python 2 and Python 3 in the same working directory? I don't see any code in [the test suite](https://github.com/zopefoundation/ZODB/blob/master/src/ZODB/tests/testdocumentation.py#L41) that would actually take care of using a temporary directory or cleaning up leftover files, so trying to build both in the same working directory would fail.

**Comment by luigino** [comment]
> Are you perhaps running these tests under both Python 2 and Python 3 in the same working directory? 

Indeed I am. Usually the automated juggling between build dirs is enough, but exceptions are always to be found, I suppose :smile:

Deleting base.fs* between tests fixes the issue for me, but what remains unclear is why it would fail seemingly at random.

**Comment by jamadden** [comment]
> what remains unclear is why it would fail seemingly at random.

Without knowing a *lot* more than I'd care too about your build process, I couldn't guess 😄 

The ZODB test suite is funky, though. I've had issues getting everything to run successfully in a virtualenv, but they do pass when run in a buildout---even though both setups use zope.testrunner and should be equivalent.
