### ISSUE TITLE
when should I close a connection?

### ISSUE THREAD

**Issue by yyz1989** [zopefoundation/ZODB#174]
Hey there,

I am new to ZODB and got a very basic question: when should I close a connection?

The behavior a bit different from other databases I have worked with. I have been struggling on it for quite some time, but still cannot get it. I definitely need a connection to create a new object and persist it into the database, for example:

```
storage = ZODB.FileStorage.FileStorage('config_db.zodb')
db = ZODB.DB(storage)
connection = db.open()
root = connection.root
root.tests = BTrees.OOBTree.BTree()
root.tests.insert("test", Test("test"))
test = root.tests.get("test")
```
But what about afterwards? I will keep this object somewhere for future access or update, then I need to have this connection open during the entire application lifecycle. If I close it, then I cannot update the object in the future:
```
connection.close()
test.name = "test2"
```
throws
```
AttributeError: 'NoneType' object has no attribute 'get'
```
But keeping that connection always open does not sound like a good idea. Or should I do that? I would really appreciate it if someone can point me to some conventions or best practices.

Thanks a lot.

Best regards,
Yang

**Comment by tseaver** [comment]
@yyz1989 It helps to think of using the ZODB using a "request / response" model.  E.g., for each request:

- At the start of the request / operation, check a connection out from the database's pool via `db.open()`.
- Perform whatever reads / writes to the objects are required to satisfy the request, or complete the operation.
- At any point, if your application raises an exception while doing this work, abort the transaction.
- Otherwise, commit the transaction (you can also abort it you know that the request / operation could / should not do persistent writes).
- Return the connection to the database pool via `connection.close()`.
- Once you have returned the connection, do *not* attempt further reads / writes on persistent objects.

**Comment by yyz1989** [comment]
@tseaver Thanks a lot for the explanation! I will try to follow it.
