### ISSUE TITLE
[DOC] Tutorial is missing a call to root

### ISSUE THREAD

**Issue by rs2** [zopefoundation/ZODB#177]
https://github.com/zopefoundation/ZODB/blame/master/doc/tutorial.rst#L86
should read `root()` instead of `root`.

**Comment by jimfulton** [comment]
You are mistaken, but understandably so. :)

The new prefered way to use root is via attributes.  Read further down in the tutorial to see what I mean.

The reasons for this:

- The root object shouldn't be used as a collection. Because:

  - Using it as a collection makes adding a second collection impossible.

  - It wasn't designed to be a collection and the data structure used isn't scalable.

- Attribute syntax is more convenient.
