### ISSUE TITLE
Possible memory leak with large data

### ISSUE THREAD

**Issue by niherus** [zopefoundation/ZODB#210]
I'm using ZODB for storage numpy arrays. The DB work quite well when I add only few arrays to it and then close DB. In this case if I open DB again then I can get access to any array I added before. However every time I add new array the memory consumption of python process is increasing rapidly until closing script or raising Memory Error.

It's strange because if add only few arrays and close script and then add more arrays etc. then I can add a lot of arrays without any problems. But if I try add same quantity of arrays without reloading script then I've got an error. (For example, I can't just add 100 arrays without errors, but I can add 10 arrays then reload script and repeat this process until I've got all 100 arrays in my DB.) 

Here is sample code (Python 3, ZODB 5.4.0) to demonstrate leakage. I used np.zeros as an example of large object. 
```
import numpy as np
import persistent, BTrees.OOBTree
import ZODB, ZODB.FileStorage, zc.zlibstorage 
import transaction
import time

import tracemalloc

tracemalloc.start()
        
sigbufs = np.zeros((45, 500000),'uint32')

storage = ZODB.FileStorage.FileStorage('C:/Users/Niherus/Desktop/data/database/sub1_2.fs')
compressed_storage = zc.zlibstorage.ZlibStorage(storage)
db = ZODB.DB(compressed_storage, large_record_size = 11152428800)
connection = db.open()
root = connection.root
root.subjects = BTrees.OOBTree.BTree()

for i in range(0,10):
    start = time.time()
    root.subjects["sub1_%s" % (i)] = sigbufs
    print("Data %s added to database" % (i))
    transaction.commit()
    stop = time.time()
    print("Changes saved. %s seconds spent" % (stop - start))
db.close()

snapshot = tracemalloc.take_snapshot()
top_stats = snapshot.statistics('lineno')

print("[ Top 10 ]")
for stat in top_stats[:10]:
    print(stat)
```
I tried to find source of leakage with Tracemalloc. Tracemalloc showed leakage somewhere in serialize.py (429 MiB) but I couldn't find objects with so large memory consumption like in Tracemalloc report.
![image](https://user-images.githubusercontent.com/9598796/44058551-174d5308-9f57-11e8-84be-d562ef5caf65.png)

Another thing that I have same problem even if I add all elements of arrays one by one. So the problem is not because of numpy but because of something else.

**Comment by jamadden** [comment]
numpy is not ZODB aware, that is, it's objects are not subclasses of `Persistent`. Each time one is pickled and then reloaded, you wind up with a new copy of the object in memory (and in the pickle). BTrees are organized in buckets, and by default an OOBTree bucket contains 30 items. So any time you make a modification to, or load any key from, a bucket, you'll get up to 30 (10 in this case because that's as many as you're using) new large copies of "sigbufs" in memory.  When you commit the transaction, you'll write out all of that data into a single pickle.

On my system, `sigbufs` reports a size of 90,000,112 bytes, while its pickle is 90,000,213 bytes. Multiplied times 10, that gives us objects with a size of 900,001,120 = 858MB and a pickle of size 900,000,623 = 858MB. Compressing with ZLIB will help on the filesystem storage of the pickles, but that data still has to be decompressed into memory, and you still wind up with 10 copies of the array data.

The fact that you're overriding `large_record_size` to be 11,152,428,800 = 10GB suggests that you saw the warnings about large, non-ZODB aware objects, and didn't understand the implications.

There are some packages that aim to make numpy objects more compatible with ZODB. One such is https://github.com/Nexedi/wendelin.core ; there may be others. I've also seen https://github.com/jimfulton/pheather for pandas.

**Comment by jimfulton** [comment]
I also have some ideas for storing numpy arrays in blobs and leveraging memory mapping to make better use of memory when working with persistent numpy arrays, if anyone's interested.

**Comment by niherus** [comment]
I'm interested. Please, tell more.

**Comment by jimfulton** [comment]
At a high level:

- Blobs give you persistent files, which provides a good scalable way to save lots of data.

- Let's assume simpler use cases, for the sake of discussion, that you want to create persistent numpy arrays and then read them a lot.

- You create an array *and* a blob.  You can open the blob for writing and pass the resulting file to numpy.save: https://docs.scipy.org/doc/numpy/reference/generated/numpy.save.html

- later you can use numpy.lib.format.open_memmap (ask for help on the function) to load the file into memory. Unfortunately, you need a file path.  For committed data, you can use the blob committed method.

- Alternatively, you can use numpy.load instead of open_memmap.
