### ISSUE TITLE
zodb.org certificate

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/ZODB#284]
Hi,
https://www.zodb.org/ has a certificate problem.
It would be great to have https by default.

Éloi

**Comment by icemac** [comment]
@jimfulton Are you able to fix the certificate of https://www.zodb.org?

**Comment by jugmac00** [comment]
Afaik we had this problem at another repository also.. but cannot recall which one.

Basically the problem is that we use the wildcard-cert from readthedocs for our own server.

So I guess either we'd have to redirect completely to the readthedocs site, or get a own cert via letsencrypt and reconfigure the web server.

**Comment by azmeuk** [comment]
A quick way out would be to redirect https://www.zodb.org to https://zodb-docs.readthedocs.io/en/latest/

**Comment by azmeuk** [comment]
I have updated the URL in the documentation so https://www.zodb.org is now https://zodb-docs.readthedocs.io , but I cannot do it on the Github project description. Can someone with enough power do this?

**Comment by mgedmin** [comment]
I can!

**Comment by azmeuk** [comment]
Thank you!
