### ISSUE TITLE
Stop python 2 support

### ISSUE THREAD

**Issue by azmeuk** [zopefoundation/ZODB#303]
The fateful end of life of python2 was 2 months ago.
Even if there is no hurry, what do you think of stopping python2 support for ZODB and related projects (BTrees, persistent etc.).
That could be a chance to do some code cleanups by removing all the compatibility layers.

What do you think?

**Comment by jamadden** [comment]
No, thank you. I will do the work to maintain Python 2 support in all those projects for the near future. 

Python 2 is still a huge part of the ecosystem, arbitrary dates aside, and those projects are foundational to lots of software. Plus, any wins from removing Python 2 support are very small at this point, because we are still supporting as far back as 3.5 so things like `f` strings are off the table.

**Comment by mgedmin** [comment]
IMHO the PSF derailed the "Python 2.x support ends 2020-Jan-1" train by announcing a final Python 2.7.x release in April 2020.  It switched me from "I will drop Python 2.x support at midnight while drinking champagne and watching fireworks" to "I'll keep more or less supporting Python 2.x until the tool ecosystem (pip, setuptools, tox, virtualenv) make it annoying".

**Comment by azmeuk** [comment]
Ok. It is good to know the intentions of the community towards python2.
