### ISSUE TITLE
Persistent object equality

### ISSUE THREAD

**Issue by mbraakhekke** [zopefoundation/ZODB#339]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

I want to assert that my persistent objects are correctly written to the file storage. Directly after committing the changes, the persistent object and the one retrieved from storage are equal. But if I close and reopen/reconnect the connection and storage, they are not. However, if test based on the `__dict__`s they are equal.
What is the correct way to assert that two persistent objects are equal? I could override `__eq__()` but the docs seem to discourage this.

### What I did:
```python
import ZODB
import ZODB.FileStorage
from persistent import Persistent
import transaction

class MyClass(Persistent):
    pass

storage = ZODB.interfaces.IStorage(ZODB.FileStorage.FileStorage("db.fs"))
connection = ZODB.connection(storage)

myClassTest = MyClass()

connection.root.myClass = myClassTest
transaction.commit()
print(connection.root.myClass == myClassTest)  # True
connection.close()
storage.close()

storage = ZODB.interfaces.IStorage(ZODB.FileStorage.FileStorage("db.fs"))
connection = ZODB.connection(storage)
print(connection.root.myClass == myClassTest)  # False
print(connection.root.myClass.__dict__ == myClassTest.__dict__)  # True
```

### What I expect to happen:

`connection.root.myClass == myClassTest` returns `True`

### What actually happened:

`connection.root.myClass == myClassTest` returns `False`

### What version of Python and Zope/Addons I am using:

Windows 10 x64
Python 3.8.6
ZODB 5.6.0

**Comment by dataflake** [comment]
AFAIK the expectation that you can do such simplistic equality testing is flawed. Just looking at the representations of `myClassTest` and `connection.root.myClass` shows me that the equality test fails because `myClassTest` still has the context of the old database connection whereas `connection.root.myClass` has the new connection as its context:

```
>>> connection.root.myClass
<__main__.MyClass object at 0x109d3a7d0 oid 0x3 in <Connection at 109e45410>>
>>> myClassTest
<__main__.MyClass object at 0x109b38bd0 oid 0x3 in <Connection at 109e45910>>
```

**Comment by jamadden** [comment]
Persistent objects inherit the default `__eq__` from `object`, unless you override it. This means that they are compared by identity (that is, `a == b` means the same as `a is b`). 

In your first example, `connection.root.myClass is myClassTest` because the object is still in the connection's cache (and still alive as a top-level object, too). In your second example, you've opened a new connection and created a new object from the stored data, so it is not the same identical object as `myClassTest`.

It's fine to override `__eq__` (and when you do that you often want to override `__hash__`) if you need a custom equality test. The documentation just brings it up because it can be a performance problem is certain cases; the default `__eq__` doesn't require loading the object from the database to determine whether it is equal to another: it's based on identity. But as soon as you override it to test attributes of the object, the object must be loaded from the database.

**Comment by mbraakhekke** [comment]
Thanks, that clarifies things. I did not know that the default implementation of `__eq__` is based on identity. 
Given the performance effects, I don't think I will override `__eq__` or `__hash__` for now. My issue is relevant in unit testing functions but is unlikely to occur in production usage. I will do my comparison in the test functions based on `__dict__`.

**Comment by agroszer** [comment]
@mbraakhekke on a sidenote, if your class has an ID-like attribute like user id, comparing that usually works too.

**Comment by mbraakhekke** [comment]
> 
> 
> @mbraakhekke on a sidenote, if your class has an ID-like attribute like user id, comparing that usually works too.

@agroszer, that's assuming that the attributes don't change after creation, right? Otherwise the ID would have to change with the state if the instance, which means it's essentially a hash.

**Comment by mbraakhekke** [comment]
> I will do my comparison in the test functions based on `__dict__`.

An addition. I found that after reconnecting to the database, the object may still be in ghost state and accessing `__dict__` is not enough to load it. `__dict__` will then return an empty `dict`. This is solved by calling `connection.root.myClass._p_activate()` which loads the state from the database.
