### ISSUE TITLE
ZODB with nogil Python

### ISSUE THREAD

**Issue by mrsipan** [zopefoundation/ZODB#379]
## FEATURE REQUEST (Maybe)

Perhaps the biggest performance bottleneck when deploying ZODB is that it can only make use of one CPU.
With the advent of _nogil_, is there any chance ZODB can be run with _nogil_ Python and thereby take advantage of multiprocessor machines?

**Comment by jimfulton** [comment]
TIL nogil

Normally, ZODB isn't a compute bottleneck. Do you have reason to believe otherwise?

ZODB is already thread safe, in that different threads can each have a connection to the same database, local or otherwise.

Whether ZODB applications can (or need to) use multiple multiple threads is up to the application.

- Applications that do a lot of network IO and aren't compute bound can get lots of concurrency even with the GIL.
- Applications that call extensions that release the GIL also can get a fair bit of concurrency.

In any case, I don't think any changes to ZODB would be necessary, as it is already thread safe.
